import './globals.css';
import { Mulish } from '@next/font/google';

const mulish = Mulish({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-mulish',
})

export const metadata = {
  title: 'Cash App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${mulish.variable}`}>
      <body>{children}</body>
    </html>
  )
}
